apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-registry-nfs
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /tank/ocp/registry
    server: kelex.revoweb.home
  persistentVolumeReclaimPolicy: Retain
