apiVersion: v1
data:
  install-config: |
    additionalTrustBundle: |
      -----BEGIN CERTIFICATE-----
      MIIDkDCCAnigAwIBAgIBATANBgkqhkiG9w0BAQUFADB8MR8wHQYDVQQKDBZLTEEt
      VEVOQ09SIENPUlBPUkFUSU9OMRMwEQYDVQQLDApLTEEtVGVuY29yMREwDwYDVQQH
      DAhNaWxwaXRhczELMAkGA1UECAwCQ0ExCzAJBgNVBAYTAlVTMRcwFQYDVQQDDA5L
      TEEtVEVOQ09SIFdFQjAeFw0xMzAzMjAyMDU3MjhaFw0yMzAzMjAyMDU3MjhaMHwx
      HzAdBgNVBAoMFktMQS1URU5DT1IgQ09SUE9SQVRJT04xEzARBgNVBAsMCktMQS1U
      ZW5jb3IxETAPBgNVBAcMCE1pbHBpdGFzMQswCQYDVQQIDAJDQTELMAkGA1UEBhMC
      VVMxFzAVBgNVBAMMDktMQS1URU5DT1IgV0VCMIIBIjANBgkqhkiG9w0BAQEFAAOC
      AQ8AMIIBCgKCAQEAhBCsNgHBOXhqYtzKwwiLjtvAh7Eigqv6PJTOVFqE1yi+QNpt
      8RqWEGOM7+szjstha8y1x8iWFL3XLDaCv0qHoErX2EGaALNFr16r6n5/EsK5QfOj
      QeamxvR4P54QiHKB2k2GkOUbpi3sSOH2hfBsZvJegcK/Jhv5G4erksDd3WyVoqxi
      EVo49cCTDewKAhVpw4edfG5gfNsiKpKm63dRHrndZkf+XiS5GWjp95BNqW7W0oc9
      nt0s1IAU+beB/jof/RS4JQRIBQX0u4RtCNsEmTuGXpUecbLezt8bxv45JmKp3KXl
      ClMVbVoWqYjPMB542b0e7NEnHgnzHns9ibqTowIDAQABox0wGzAMBgNVHRMEBTAD
      AQH/MAsGA1UdDwQEAwIBBjANBgkqhkiG9w0BAQUFAAOCAQEAWbhqgPYsOXw1YvI/
      QTHIMn5aCrj6xImTNDPuw25KIe9L3VIYtMtiOUovOO47CZUkcyMxgjsa04VA/Oqr
      Z1GFEYnu6QGJtKa2GXxwcaKbTyA7doES6hv4nh0H2zAQiZ0ivbu/BVpQBo92hKwJ
      l2JkcgW5YUa0w6Vxa7Cglh9VHUHho0P/jPx3tIG7gWoiDa7TTq1aALXvuvFrb6Xs
      DjJ9ozJSZucIe6ZVTE2XSMDtkOvx5P53KHhyVGlmAs9XDGbAwgkDpHb6Zxe9Xx9J
      1zsDobTy6vrG6F4X/a8AdKgQeB4tLImH5OVuzLXY9nGSuAZFileBoYNx245qhIjR
      iGoMqg==
      -----END CERTIFICATE-----
    apiVersion: v1
    baseDomain: kla-tencor.com
    compute:
    - hyperthreading: Enabled
      name: worker
      platform: {}
      replicas: 1
    controlPlane:
      hyperthreading: Enabled
      name: master
      platform: {}
      replicas: 3
    metadata:
      creationTimestamp: null
      name: ocp4
    networking:
      clusterNetwork:
      - cidr: 10.254.0.0/16
        hostPrefix: 24
      clusterNetworks:
      - cidr: 10.254.0.0/16
        hostPrefix: 24
      machineCIDR: 10.0.0.0/16
      networkType: OpenShiftSDN
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      none: {}
    publish: External
    pullSecret: ""
    sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDaHQl8CynkbXVqQbzkiIDzfJfYZ1bM502lrF8ONACqO7j4xzfRZawWl9TIdwAbCv26fWlqy7h4YjUuFH1eflTfV569uBQF51mqE4266cVDuXNZSWWYMa+8NK8u7TP/mCjmmZN2rFAy996FScmFMK6N+LVZdhOSjwizZui3N0UCRL47RrNjMAjiI3QfCNwat8g0JdC4j+lG6G3o+DDjYxlgoPbCiP1BN7/ifra/RjQD3oWFUDPm2W8dffbKzIldmXyaoWJkHUdt622BQLTc4TnCMCiBzAz9XHIqf9IY9MURyjEOt0MBUIqDNLcXngnkCv/gX6QwVl+NXFhDkwfds2ZR
      root@helper
kind: ConfigMap
metadata:
  name: cluster-config-v1
  namespace: kube-system
