apiVersion: v1
kind: Pod
metadata:
  name: sriovsamplepod3
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net3
spec:
  containers:
  - name: sriovsamplepo3
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: centos/tools
    resources:
      requests:
        openshift.io/sriov: '1'
      limits:
        openshift.io/sriov: '1'
