apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/sriov
  creationTimestamp: "2019-10-03T01:36:02Z"
  generation: 1
  name: sriov-net3
  namespace: sriov-network-operator
  resourceVersion: "4831807"
spec:
  config: '{ "type": "sriov", "name": "sriov-net1", "ipam": { "type": "host-local" }, "subnet": "192.168.10.0/24", "rangeStart": "192.168.10.60", "rangeEnd": "192.168.10.70", "routes": [ { "dst": "0.0.0.0/0"}, { "dst": "192.168.10.0/24", "gw": "192.168.10.1"} ], "dataDir": "/run/container-ipam-state" }'
