apiVersion: v1
kind: Pod
metadata:
  name: pod7
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-test
spec:
  containers:
  - name: testpmd
    image: centos/tools
    imagePullPolicy: Never
    securityContext:
     capabilities:
        add: ["IPC_LOCK"]
    command: ["sleep", "infinity"]
    resources:
      requests:
        openshift.io/sriov: '1'
      limits:
        openshift.io/sriov: '1'
