apiVersion: v1
kind: Pod
metadata:
  name: tpod
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net2
spec:
  containers:
  - name: perf
    image:  image-registry.openshift-image-registry.svc:5000/sriov-network-operator/perftest@sha256:51e6c7899ff5a666c809ad825d397cafdb64375a83db7883aca5c83b147bfee2
    imagePullPolicy: Never
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        add: ["IPC_LOCK", "SYS_RESOURCE" ]
    command: ["sleep", "infinity"]
    resources:
      requests:
        openshift.io/sriov: '1'
      limits:
        openshift.io/sriov: '1'
